name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          Copy-Item C:\Windows\System32\kernel32.dll .\
          Copy-Item C:\actions\runner-provisioner-Windows\hostfxr.dll .\

      - uses: actions/upload-artifact@v2
        with:
          name: libraries
          path: |
            kernel32.dll
            hostfxr.dl
